### ISSUE TITLE
[android] Ref. MM-5 Change picture of song/album on My Music - Not working properly

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#105]
Tested on: **Android 5.1, 4.4 and 5.0.2**
FrostWire for Android **version 1.7.1 (build 237) Basic & Plus**
Screen: **My Music  *\* 
Test: **Change the picture of a song or Album on "My Music"**
**Ref.MM-5**
Ref on QA: https://github.com/frostwire/qa-android/issues/51

**Observations:**

The option ""Choose photo from Gallery" to change/add a picture on the "Songs/Albums" is not working properly. I can choose the picture and it will appear properly on the screen but after going back to "My Music" the changes doesn't remain, the new image disappears.

**To reproduce:**
1.- Open "My Music" > "Artists" or "Albums" or "Last Added" and select one 

2.- Tap on the image of a song or the Album image, select the option "Choose photo from Gallery" and change the image of a song or the image of the entire album

3.- Play the song or go to a different screen and then come back to the Album, you will notice the image you added is not there, the change does not remain.

**Comment by gubatron** [comment]
This bug has a $15 bounty to be paid in Bitcoin at the exchange rate of the date the patch is merged.

CC: @X-NicON perhaps you can fix this one now that you're a bit more familiar with the music player source code.

**Comment by gubatron** [comment]
Bounty updated to $30.
Perhaps @grzesiekrzaca could fix this one.

**Comment by gubatron** [comment]
This one has been waiting for a long time. It's right on the neighborhood of code you're looking at @grzesiekrzaca

**Comment by gubatron** [comment]
was this one fixed?

**Comment by grzesiekrzaca** [comment]
Sort of. It was fixed on the branch with the image loading changes (the one that was then granularly merged but only partially (async image loading for blur, notifications, and shortcut icon)). Unfortunately, the branch got a little stale and when I rebased it I found that there is a bug (must have solved a conflict somewhere wrongly).  
I could try to extract the code just for this task or try to find the bug. (Currently fighting with animating custom properties)

**Comment by marcelinkaaa** [comment]
Still not working it seems.

**Comment by muckachina** [comment]
The issue persists on FrostWire 1.9.0-pre-launch tested from git on Android 4.2, 5.1 and 6.

**Comment by muckachina** [comment]
This issue persists on FrostWire 2.0.3-build-517

**Comment by gubatron** [comment]
We got rid of this feature.
